### ISSUE TITLE
ValueError: columns overlap but no suffix specified

### ISSUE THREAD

**Issue by ykm7788** [bluenote-1577/sylph-utils#4]
When using `merge_sylph_taxprof.py`, I ran into this error：

> 

Traceback (most recent call last):
  File "/home/ykm/software/sylph-utils/merge_sylph_taxprof.py", line 42, in <module>
    main()
  File "/home/ykm/software/sylph-utils/merge_sylph_taxprof.py", line 36, in main
    merged_df = merge_data(args.files, args.column)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ykm/software/sylph-utils/merge_sylph_taxprof.py", line 24, in merge_data
    merged_df = merged_df.join(df, how='outer')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/frame.py", line 9729, in join
    return self._join_compat(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/frame.py", line 9768, in _join_compat
    return merge(
           ^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 162, in merge
    return op.get_result(copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 811, in get_result
    result = self._reindex_and_concat(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 763, in _reindex_and_concat
    llabels, rlabels = _items_overlap_with_suffix(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sysoft/Python-3.11.4/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 2604, in _items_overlap_with_suffix
    raise ValueError(f"columns overlap but no suffix specified: {to_rename}")
ValueError: columns overlap but no suffix specified: Index(['data.clean.1.fq.gz'], dtype='object')

So I modified the python script in line24 to:
`            merged_df = merged_df.join(df, how='outer', rsuffix='_right')`
and it worked.

I'm not sure if this is a good way but perhaps you can check.

**Comment by bluenote-1577** [comment]
Hi @ykm7788 

Thanks for the bug report. Can you tell me what the sample names for your *.sylphmpa files are? This error is produced when you do `python merge_sylph_taxprof.py sample.sylphmpa sample.sylphmpa ...` with two samples with the same samplename. Maybe I can make the error output more informative.

**Comment by ykm7788** [comment]
> Hi @ykm7788
> 
> Thanks for the bug report. Can you tell me what the sample names for your *.sylphmpa files are? This error is produced when you do `python merge_sylph_taxprof.py sample.sylphmpa sample.sylphmpa ...` with two samples with the same samplename. Maybe I can make the error output more informative.

Hello @bluenote-1577 

The folder is like:
fungi.tsv
fungi_MYSAMPLE.clean.1.fq.gz.sylphmpa
gtdb.tsv
gtdb_MYSAMPLE.clean.1.fq.gz.sylphmpa
imgvr.tsv
imgvr_MYSAMPLE.clean.1.fq.gz.sylphmpa
ocean.tsv
ocean_MYSAMPLE.clean.1.fq.gz.sylphmpa
smag.tsv
smag_MYSAMPLE.clean.1.fq.gz.sylphmpa

As you can see, the files are unique.

**Comment by bluenote-1577** [comment]
I see. The problem is that MYSAMPLE is the same sample name, and you probably ran `sylph_to_taxprof` for each sample database.

Try this instead:

`python sylph_to_taxprof.py -m gtdb...tsv.gz fungi...tsv.gz imgvr....tsv.gz ... -s sylph_output.tsv -o prefix_or_folder/`

You can use multiple metadata files and combine them. `merge_sylph_taxprof` is for merging _across differnt samples_, not different databases.

I'll look for how to best fix this issue
